### ISSUE TITLE
jetpack support

### ISSUE THREAD

**Issue by markryall** [Automattic/wp-telegram-bot#6]
At the moment, new posts on a jetpack site do not seem to be published to telegram.

XMPP does support this so it might relate to a problem with the stored mapping between the original subscription url and the correct telegram channel.

some examples:

- integers.blog atomic site actually creates a subscription to markryallfancybusiness.wordpress.com
- ~~ryall.name/wp didn't seem to work either~~ seems to be resolved by #7

**Comment by yurynix** [comment]
@markryall #14 solves that, right?

**Comment by markryall** [comment]
Yep it does - sites such as integers.blog actually creating a subscription to markryallfancybusiness.wordpress.com seems a separate issue that needs to be dealt with elsewhere
